Update 3-redirection

diff --git a/web_server/3-redirection b/web_server/3-redirection
--- a/web_server/3-redirection
+++ b/web_server/3-redirection
@@ -1,26 +1,33 @@
 #!/usr/bin/env bash
-# Configure Nginx server so that /redirect_me is redirecting to another page
-
-sudo apt-get update -y
+# Install Nginx
+sudo apt-get update
 sudo apt-get install -y nginx
-sudo ufw allow 'Nginx HTTP'
-config=\
-"server {
-        listen 80 default_server;
-        listen [::]:80 default_server;
-	root /var/www/html;
-	index index.html index.htm index.nginx-debian.html;
-	server_name _;
-	location / {
-		try_files \$uri \$uri/ =404;
-        }
-	location /redirect_me {
-		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
-	}
+
+# Configure Nginx redirection
+sudo tee /etc/nginx/sites-available/redirection <<EOF
+server {
+    listen 80;
+    server_name _; # Default server_name to catch all requests
+
+    location /redirect_me/ {
+        return 301 http://new_domain.com/new_path;
+    }
 }
-"
-sudo chown -R "$USER":"$USER" /var/www/html/index.html
-sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
-echo "Holberton School" > /var/www/html/index.html
-echo "$config" > /etc/nginx/sites-available/default
-sudo service nginx restart
+EOF
+
+# Remove default server configuration to avoid conflicts
+sudo rm /etc/nginx/sites-enabled/default
+
+# Create a symbolic link to enable the configuration
+sudo ln -sf /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/
+
+# Test Nginx configuration
+sudo nginx -t
+
+# Check if Nginx configuration test passed
+if [ $? -eq 0 ]; then
+    # Reload Nginx to apply changes
+    sudo service nginx reload
+else
+    echo "Nginx configuration test failed. Please check your configuration."
+fi
